[general]
pidfile="burrow.pid"

[logging]
filename="/opt/burrow/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "172.22.107.71:2181", "172.22.107.72:2181", "172.22.107.73:2181", "172.22.107.74:2181", "172.22.107.75:2181" ]
timeout=6
root-path="/burrow"

[client-profile.kafka_monitor]
client-id="kafka_monitor"
kafka-version="1.0.0"
sasl="sasl_kafka"

[sasl.sasl_kafka]
username="kafka"
password="pneekcpt"
handshake-first=true

[cluster.docker]
class-name="kafka"
servers=[ "172.22.107.73:9092", "172.22.107.74:9092", "172.22.107.75:9092" ]
client-profile="kafka_monitor"
topic-refresh=120
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="docker"
servers=[ "172.22.107.73:9092", "172.22.107.74:9092", "172.22.107.75:9092" ]
client-profile="kafka_monitor"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[consumer.local_zk]
class-name="kafka_zk"
cluster="docker"
servers=[ "172.22.107.71:2181", "172.22.107.72:2181", "172.22.107.73:2181", "172.22.107.74:2181", "172.22.107.75:2181" ]
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[httpserver.default]
address=":1199"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1
